src/AppBundle/Entity/Pozo.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Base\BaseClass;
use Doctrine\ORM\Mapping as ORM;

/**
 * Pozo
 *
 * @ORM\Table(name="pozo")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\PozoRepository")
 */
class Pozo extends BaseClass
{

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=255)
     */
    private $nombre;

    /**
     * @var string
     *
     * @ORM\Column(name="acronimo", type="string", length=25)
     */
    private $acronimo;

    /**
     * @var string
     *
     * @ORM\Column(name="profundidad", type="string", length=10)
     */
    private $profundidad;

    /**
     * @var stringd
     *
     * @ORM\Column(name="sistema_extraccion", type="string", length=50)
     */
    private $sistemaExtraccion;

    /**
     * @var string
     *
     * @ORM\Column(name="latitud", type="string", length=50)
     */
    private $latitud;


    /**
     * @var string
     *
     * @ORM\Column(name="longitud", type="string", length=50)
     */
    private $longitud;

    /**
     * @var
     *
     * @ORM\ManyToOne( targetEntity="AppBundle\Entity\Yacimiento", inversedBy="pozos")
     * @ORM\JoinColumn(name="yacimiento_id", referencedColumnName="id", nullable=false)
     */
    private $yacimiento;

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Intervencion", mappedBy="pozo")
     */
    private $intervenciones;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set nombre
     *
     * @param string $nombre
     *
     * @return Pozo
     */
    public function setNombre($nombre)
    {
        $this->nombre = $nombre;

        return $this;
    }

    /**
     * Get nombre
     *
     * @return string
     */
    public function getNombre()
    {
        return $this->nombre;
    }

    /**
     * Set acronimo
     *
     * @param string $acronimo
     *
     * @return Pozo
     */
    public function setAcronimo($acronimo)
    {
        $this->acronimo = $acronimo;

        return $this;
    }

    /**
     * Get acronimo
     *
     * @return string
     */
    public function getAcronimo()
    {
        return $this->acronimo;
    }

    /**
     * Set profundidad
     *
     * @param string $profundidad
     *
     * @return Pozo
     */
    public function setProfundidad($profundidad)
    {
        $this->profundidad = $profundidad;

        return $this;
    }

    /**
     * Get profundidad
     *
     * @return string
     */
    public function getProfundidad()
    {
        return $this->profundidad;
    }

    /**
     * Set sistemaExtraccion
     *
     * @param string $sistemaExtraccion
     *
     * @return Pozo
     */
    public function setSistemaExtraccion($sistemaExtraccion)
    {
        $this->sistemaExtraccion = $sistemaExtraccion;

        return $this;
    }

    /**
     * Get sistemaExtraccion
     *
     * @return string
     */
    public function getSistemaExtraccion()
    {
        return $this->sistemaExtraccion;
    }

    /**
     * Set latitud
     *
     * @param string $latitud
     *
     * @return Pozo
     */
    public function setCoordenadas($latitud)
    {
        $this->latitud = $latitud;

        return $this;
    }

    /**
     * Get latitud
     *
     * @return string
     */
    public function getLatitud()
    {
        return $this->latitud;
    }


    /**
     * Set longitud
     *
     * @param string $longitud
     *
     * @return Pozo
     */
    public function setLongitud($longitud)
    {
        $this->longitud = $longitud;

        return $this;
    }

    /**
     *
     * Get longitud
     *
     * @return string
     */
    public function getLongitud()
    {
        return $this->longitud;
    }

    /**
     * Set yacimiento
     *
     * @param \AppBundle\Entity\Yacimiento $yacimiento
     *
     * @return Pozo
     */
    public function setYacimiento(\AppBundle\Entity\Yacimiento $yacimiento = null)
    {
        $this->yacimiento = $yacimiento;

        return $this;
    }

    /**
     * Get yacimiento
     *
     * @return \AppBundle\Entity\Yacimiento
     */
    public function getYacimiento()
    {
        return $this->yacimiento;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->intervenciones = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Set latitud
     *
     * @param string $latitud
     *
     * @return Pozo
     */
    public function setLatitud($latitud)
    {
        $this->latitud = $latitud;

        return $this;
    }


    /**
     * Add intervencione
     *
     * @param \AppBundle\Entity\Intervencion $intervencione
     *
     * @return Pozo
     */
    public function addIntervencione(\AppBundle\Entity\Intervencion $intervencione)
    {
        $this->intervenciones[] = $intervencione;

        return $this;
    }

    /**
     * Remove intervencione
     *
     * @param \AppBundle\Entity\Intervencion $intervencione
     */
    public function removeIntervencione(\AppBundle\Entity\Intervencion $intervencione)
    {
        $this->intervenciones->removeElement($intervencione);
    }

    /**
     * Get intervenciones
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getIntervenciones()
    {
        return $this->intervenciones;
    }

    /**
     *
     *
     * @return Intervencion|null
     */
    public function getUltimaIntervencion(){

        $intervencion = null;

        if( $this->getIntervenciones()->count()){
            $intervencion = $this->getIntervenciones()->last();
        }

        return $intervencion;
    }

    /**
     * Busca la accion de la ultima intervencion realizada en el pozo
     *
     *
     * @return int 0 (abierto) 1 (cerrado)
     */
    public function getEstadoUltimaIntervencion(){

        $estado = 1; //Por defecto el pozo se encuentra cerrado

        $ultimaIntervencion = $this->getUltimaIntervencion();

        if($ultimaIntervencion){
           $estado = $ultimaIntervencion->getAccion();
        }

        return $estado;
    }


    public function estaAbierto(){
        return !$this->getEstadoUltimaIntervencion();
    }


    public function __toString()
    {
        return $this->getNombre();
    }

	/**
	 * Retorna la intervencion asociada al equipo en el caso de que esté interviniendo.
	 * False en el caso de que no esté activo en algun Pozo
	 *
	 * @return bool| Intervencion
	 */
	public function getIntervencionActual()
	{

		$intervencion =  $this->getIntervenciones()->last();


		if( $intervencion && $intervencion->esApertura()){
			return $intervencion;
		}

		return false;
	}

}

src/AppBundle/Form/PersonaType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Valid;
use UsuarioBundle\Form\UsuarioType;

class PersonaType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nombre')
            ->add('apellido')
            ->add('sexo', ChoiceType::class, array(
                'choices' => array(
                    'Masculino' => 'M' ,
                    'Femenino'  => 'F'
                ),
                'choices_as_values' => true
            ))
            ->add('telefonoPrincipal')
            ->add('telefonoSecundario')
	        ->add('compania')
            ->add('cargo')
            ->add('usuario', UsuarioType::class, array())
        ;
    }
    
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Persona'
        ));
    }
}

src/AppBundle/Controller/PersonaController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Configuracion;
use AppBundle\Event\PersonaActualizadaEvent;
use AppBundle\Event\PersonaCreadaEvent;
use AppBundle\Event\PersonaEliminadaEvent;
use AppBundle\Form\ConfiguracionType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

use AppBundle\Entity\Persona;
use AppBundle\Form\PersonaType;

/**
 * Persona controller.
 *
 */
class PersonaController extends Controller
{
    /**
     * Lists all Persona entities.
     *
     */
    public function indexAction(Request $request)
    {
        $em = $this->getDoctrine()->getManager();

	    $roles = $em->getRepository('UsuarioBundle:Rol')->findAll();

        $personas = $em->getRepository('AppBundle:Persona')->findAll();

        $paginator = $this->get('knp_paginator');

        $personas = $paginator->paginate(
            $personas,
            $request->query->get('page', 1)/* page number */,
            10/* limit per page */
        );

        $deleteForm = $this->createDeleteForm();

        return $this->render('AppBundle:persona:index.html.twig', array(
            'personas'    => $personas,
            'delete_form' => $deleteForm->createView(),
	        'roles'       => $roles
        ));
    }

    /**
     * Creates a new Persona entity.
     *
     */
    public function newAction(Request $request)
    {
        $persona = new Persona();
        $form = $this->createForm(PersonaType::class, $persona);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

	        $rol = $form->get('usuario')->get('roles')->getData();

	        $persona->getUsuario()->setRoles(array());
	        $persona->getUsuario()->addRole($rol);

        	$em = $this->getDoctrine()->getManager();

	        $configuracion = new Configuracion();

	        $configuracion->setPersona($persona);

	        $persona->setConfiguracion($configuracion);

            $em->persist($persona);

	        $em->flush();

	        $dispatcher = $this->get('event_dispatcher');

	        $event = new PersonaCreadaEvent($persona);

	        $dispatcher->dispatch(PersonaCreadaEvent::NAME, $event);

            // set flash messages
            $this->get('session')->getFlashBag()->add('success', 'El registro se ha guardado satisfactoriamente.');

            return $this->redirectToRoute('persona_index');

        }

        return $this->render('AppBundle:persona:new.html.twig', array(
            'persona' => $persona,
            'form' => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Persona entity.
     *
     */
    public function showAction(Persona $persona)
    {


        return $this->render('AppBundle:persona:show.html.twig', array(
            'persona' => $persona
        ));
    }

    /**
     * Displays a form to edit an existing Persona entity.
     *
     */
    public function editAction(Request $request, Persona $persona)
    {
        $deleteForm = $this->createDeleteForm($persona);
        $editForm = $this->createForm(PersonaType::class, $persona);
        $editForm->handleRequest($request);

        if ($editForm->isSubmitted() && $editForm->isValid()) {

            $rol = $editForm->get('usuario')->get('roles')->getData();

            $persona->getUsuario()->setRoles(array());
            $persona->getUsuario()->addRole($rol);
            
            $em = $this->getDoctrine()->getManager();
            $em->persist($persona);
            $em->flush();

            // set flash messages
            $this->get('session')->getFlashBag()->add('success', 'El registro se ha actualizado satisfactoriamente.');

            return $this->redirectToRoute('persona_edit', array('id' => $persona->getId()));
        }

        return $this->render('AppBundle:persona:edit.html.twig', array(
            'persona' => $persona,
            'edit_form' => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    /**
     * Deletes a Persona entity.
     *
     */
    public function deleteAction(Request $request, Persona $persona)
    {
        $form = $this->createDeleteForm($persona);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try{
                $em = $this->getDoctrine()->getManager();

                $em->remove($persona);

	            $dispatcher = $this->get('event_dispatcher');

	            $event = new PersonaEliminadaEvent($persona);

	            $dispatcher->dispatch(PersonaEliminadaEvent::NAME, $event);

                $em->flush();

                $this->get('session')->getFlashBag()->add('success', 'El registro se ha dado de baja satisfactoriamente.');
            }catch(\Exception $e){

                $this->get('session')->getFlashBag()->add('error', 'Hubo un error al intentar eliminar el registro.');
            }
        }

        return $this->redirectToRoute('persona_index');
    }

    /**
     * Creates a form to delete a Persona entity.
     *
     *
     * @return \Symfony\Component\Form\Form The form
     */
    private function createDeleteForm()
    {
        return $this->createFormBuilder()
            ->setAction($this->generateUrl('persona_delete', array('id' => '__obj_id__')))
            ->setMethod('DELETE')
            ->getForm()
        ;
    }



    /**
     * Lists all Persona entities.
     *
     */
    public function perfilAction(Request $request)
    {

    	$persona = $this->getUser()->getPersona();

	    $configuracion = $persona->getConfiguracion();

	    if(!$configuracion){

	    	$configuracion = new Configuracion();

		    $configuracion->setPersona($persona);

	    }

    	$form = $this->createForm(ConfiguracionType::class,$configuracion);

	    $form->handleRequest($request);

	    if ($form->isSubmitted() && $form->isValid()) {

		    $em = $this->getDoctrine()->getManager();


		    $config = array();


		    foreach ($form->getIterator() as $key => $child) {

			    $config[$key] = $child->getData();
		    }

	    	$configuracion->setPersona($persona);

		    $configuracion->setConfiguracion($config);

		    $em->persist($configuracion);

		    $em->flush();

	    }

        return $this->render('AppBundle:persona:perfil.html.twig', array(
        	'form'      => $form->createView(),
	        'persona'   => $persona
        ));
    }
}

src/AppBundle/Resources/views/persona/edit.html.twig
{% extends 'base.html.twig' %}


{% set __title = 'Editar Persona' %}

{% block content %}
<div class="box box-default">
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <!-- form start -->
                {{ form_start(edit_form) }}
                {{ form_widget(edit_form) }}
                <div class="box-footer">
                    <input class="btn btn-primary" type="submit" value="Editar"/>
                    <a class="btn btn-default" href="{{ path('persona_index') }}"> Volver al Listado</a>
                </div>

                {{ form_end(edit_form) }}
            </div>
        </div>
    </div>
</div>

{% endblock %}

src/AppBundle/Resources/views/persona/index.html.twig
{% extends 'base.html.twig' %}

{% import _self as listado %}

{% set __title = 'Listado de Personas' %}

{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Username</th>
                                <th>Rol</th>
                                <th>Nombre</th>
                                <th>Apellido</th>
                                <th>Tel. Principal</th>
                                <th>Cargo</th>
                                <th>Habilitado</th>
                                <th>Creado</th>
                                <th>Actualizado</th>
                                <th>Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for persona in personas %}
                            <tr>
                                <td>{{ persona.id }}</td>
                                <td><a href="{{ path('persona_show', { 'id': persona.id }) }}">{{ persona.usuario.username }}</a></td>
                                <td> {{ listado.userFriendlyRol(persona.usuario.roles[0],roles) }}</td>
                                    {#<a href="{{ path('rol_show', { 'id': persona.usuario.roles.[0].id }) }}">{{ persona.usuario.roles.[0] }}</a></td>#}
                                <td>{{ persona.nombre }}</td>
                                <td>{{ persona.apellido }}</td>
                                <td>{{ persona.telefonoPrincipal }}</td>
                                <td>{{ persona.cargo }}</td>
                                <td>{% if persona.usuario.enabled %}<span class="label label-success">Si</span{% else %}<span class="label label-danger">No</span>{% endif %}</td>
                                <td>{% if persona.fechaCreacion %}{{ persona.fechaCreacion|date('d/m/Y') }}{% endif %}</td>
                                <td>{% if persona.fechaActualizacion %}{{ persona.fechaActualizacion|date('d/m/Y') }}{% endif %}</td>
                                <td>
                                    <a title="Editar"   class="btn btn-default btn-sm" href="{{ path('persona_edit', { 'id': persona.id }) }}"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <a title="Cambiar Password" class="btn btn-default btn-sm" href="{{ path('cambiar-password', { 'id': persona.usuario.id }) }}"><i class="fa fa-fw fa-key"></i></a>
                                    <a title="Eliminar" class="btn btn-default btn-sm delete-obj" data-id="{{ persona.id }}" data-href="{{ path('persona_delete', { 'id': persona.id }) }}"> <i class="glyphicon glyphicon-remove-circle"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
            {{ knp_pagination_render(personas) }}

        </div>
    </div>

    <div class="delete-obj-form hidden">
        {{ form_start(delete_form) }}
        <input type="submit" value="Delete">
        {{ form_end(delete_form) }}
    </div>

    <a class="btn btn-primary" href="{{ path('persona_new') }}">Nueva Persona</a>

{% endblock %}

{% macro userFriendlyRol(rol_slug,roles) %}
    {% for  rol in roles %}
        {% if rol.slug == rol_slug %}
            {{ rol.nombre }}
        {% endif %}
    {% endfor %}
{% endmacro %}

src/AppBundle/Resources/views/persona/new.html.twig
{% extends 'base.html.twig' %}


{% set __title = 'Nueva Persona' %}

{% block content %}
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-md-6">
                    <!-- form start -->
                    {{ form_start(form) }}
                    {{ form_widget(form) }}
                    <div class="box-footer">
                        <input class="btn btn-primary" type="submit" value="Crear"/>
                        <a class="btn btn-default" href="{{ path('persona_index') }}"> Volver al Listado</a>
                    </div>

                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/persona/show.html.twig
{% extends 'base.html.twig' %}

{% set __title = 'Persona' %}

{% block content %}
<div class="box box-default">
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <table class="table">
                    <tbody>
                        <tr>
                            <th>Id</th>
                            <td>{{ persona.id }}</td>
                        </tr>
                        <tr>
                            <th>Username:</th>
                            <td>{{ persona.usuario.username }}</td>
                        </tr>
                        <tr>
                            <th>Nombre</th>
                            <td>{{ persona.nombre }}</td>
                        </tr>
                        <tr>
                            <th>Apellido</th>
                            <td>{{ persona.apellido }}</td>
                        </tr>
                        <tr>
                            <th>Cargo</th>
                            <td>{{ persona.cargo }}</td>
                        </tr>
                        <tr>
                            <th>Compañía</th>
                            <td><a href="{{ path('compania_show', { 'id': persona.compania.id }) }}">{{ persona.compania.nombre }}</a></td>
                        </tr>
                        <tr>
                            <th>Tel. Principal</th>
                            <td>{{ persona.telefonoPrincipal }}</td>
                        </tr>
                        <tr>
                            <th>Tel. Secundario</th>
                            <td>{{ persona.telefonoSecundario }}</td>
                        </tr>
                        <tr>
                            <th>Habilitado</th>
                            <td>{% if persona.usuario.enabled %}<span class="label label-success">Si</span{% else %}<span class="label label-danger">No</span>{% endif %}</td>
                        </tr>
                        <tr>
                            <th>Creado</th>
                            <td>{% if persona.fechaCreacion %}{{ persona.fechaCreacion|date('d/m/Y H:i:s') }}{% endif %}</td>
                        </tr>
                        <tr>
                            <th>Actualizado</th>
                            <td>{% if persona.fechaActualizacion %}{{ persona.fechaActualizacion|date('d/m/Y H:i:s') }}{% endif %}</td>
                        </tr>
                        <tr>
                            <th>Creado Por</th>
                            <td>{% if persona.creadoPor %}<a href="{{ path('persona_show', { 'id': persona.creadoPor.persona.id }) }}">{{ persona.creadoPor.persona }}</a>{% endif %}</td>
                        </tr>
                        <tr>
                            <th>Actualizado Por</th>
                            <td>{% if persona.actualizadoPor %}<a href="{{ path('persona_show', { 'id': persona.actualizadoPor.persona.id }) }}">{{ persona.actualizadoPor.persona }}</a>{% endif %}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="box-footer">
                    <a class="btn btn-primary" href="{{ path('persona_edit', { 'id': persona.id }) }}"> Editar</a>
                    <a class="btn btn-default" href="{{ path('persona_index') }}"> Volver al Listado</a>
                </div>

            </div>
            <div class="col-md-6">

                    {#{{ equipo }}#}
                    <!-- TABLE: LATEST ORDERS -->
                    <div class="box no-border">
                        <div class="box-header with-border">
                            <h3 class="box-title">Equipos Asignados</h3>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <div class="table-responsive">
                                <table class="table no-margin">
                                    <thead>
                                    <tr>
                                        <th>Equipo</th>
                                        <th>Modelo</th>
                                        <th>Activo</th>
                                        <th>Pozo</th>
                                        <th>Intervenido el</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for equipo in persona.equipos %}
                                    <tr>
                                        <td><a href="{{ path('equipo_show', { 'id': equipo.id }) }}">{{ equipo.nombreCompleto | upper }}</td>
                                        <td>{{ equipo.modelo }}</td>
                                        <td>{% if equipo.activo %}<span class="label label-success">Si</span{% else %}<span class="label label-danger">No</span>{% endif %}</td>
                                        <td>
                                            {%  if equipo.intervencionActual %}
                                                <a href="{{ path('pozo_show', { 'id': equipo.intervencionActual.pozo.id }) }}">{{ equipo.intervencionActual.pozo }}</a>
                                            {% else %}
                                                -
                                            {% endif %}
                                        </td>
                                        <td>
                                            {%  if equipo.intervencionActual %}
                                                {{ equipo.intervencionActual.fecha |date('d/m/Y H:i:s')  }}
                                            {% else %}
                                                -
                                            {% endif %}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.box-body -->
                    </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}